//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcessObject
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Donors
    {
        public int Donor_id { get; set; }
        public string First_name { get; set; }
        public string Last_name { get; set; }
        public string Email { get; set; }
        public string Contact { get; set; }
        public string Gender { get; set; }
        public string Address { get; set; }
        public string Blood_group { get; set; }
        public Nullable<System.DateTime> Added_date { get; set; }
        public string Image_name { get; set; }
        public Nullable<int> Added_by { get; set; }
    }
}
